#!/bin/bash
# Forked from https://github.com/mdaffin/salt-arch
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

fail() {
  echo >&2 "$@"
  exit 1
}

if grep -qs /mnt /proc/mounts; then
    fail "/mnt is already mounted. Unmount it first, or edit this script."
fi

if [ ! -f laptop-pillar-secrets.gpg ]; then
    fail "Missing laptop-pillar-secrets.gpg. Copy into current dir and try again"
fi

gpgKeyUrl=https://keybase.io/atmoz/pgp_keys.asc
saltStateRepo=https://github.com/atmoz/salt-laptop.git

devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
device=$(dialog --stdout --menu "Select installtion disk" 0 0 0 ${devicelist}) || exit 1
clear

### Setup the disk and partitions ###
parted --script "${device}" -- mklabel gpt \
    mkpart primary bios_grub 1Mib 2MiB \
    set 1 boot on \
    mkpart primary ext4 2MiB 10GiB \
    mkpart primary ext4 10GiB 100%

# Simple globbing was not enough as on one device I needed to match /dev/mmcblk0p1
# but not /dev/mmcblk0boot1 while being able to match /dev/sda1 on other devices.
part_boot="$(ls ${device}* | grep -E "^${device}p?1$")"
part_root="$(ls ${device}* | grep -E "^${device}p?2$")"
part_home="$(ls ${device}* | grep -E "^${device}p?3$")"

mkfs.ext4 "${part_root}"
mkfs.ext4 "${part_home}"

mount "${part_root}" /mnt
pacstrap /mnt base grub salt git gnupg
genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt sh -c "grub-install --target=i386-pc $device \
    && grub-mkconfig -o /boot/grub/grub.cfg"

arch-chroot /mnt sh -c "curl $gpgKeyUrl | gpg --import"
arch-chroot /mnt sh -c "git clone $saltStateRepo /srv/salt"
if ! arch-chroot /mnt sh -c "cd /srv/salt && git verify-commit HEAD"; then
    fail "GPG signature check failed!"
fi

cat >/mnt/etc/salt/minion <<EOF
file_client: local
file_roots:
  base:
    - /srv/salt/states
pillar_roots:
  base:
    - /srv/salt/pillar
EOF

# Use pinentry-curses to unlock yubikey
rm /usr/bin/pinentry
ln -s /usr/bin/pinentry-curses /usr/bin/pinentry

curl $gpgKeyUrl | gpg --import
gpg -d /tmp/laptop-pillar-secrets.gpg > /srv/salt/pillar/secrets.sls

arch-chroot /mnt sh -c "salt-call state.apply pillar='{\"bootstrap\": True}'"
